// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAs4wsPGi8H63g--B9N2DT50fm9ZRNh6Mg',
    appId: '1:169717028719:web:5e65834a8a9398cdfdfa9a',
    messagingSenderId: '169717028719',
    projectId: 'walkapp-9a996',
    authDomain: 'walkapp-9a996.firebaseapp.com',
    storageBucket: 'walkapp-9a996.appspot.com',
    measurementId: 'G-RD8EJGXXTX',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlAu1YHUXwF-LTm_hvK37QOsGSvpwa-QY',
    appId: '1:169717028719:ios:2020a4fad7ce9281fdfa9a',
    messagingSenderId: '169717028719',
    projectId: 'walkapp-9a996',
    storageBucket: 'walkapp-9a996.appspot.com',
    iosBundleId: 'com.example.walkingapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlAu1YHUXwF-LTm_hvK37QOsGSvpwa-QY',
    appId: '1:169717028719:ios:2020a4fad7ce9281fdfa9a',
    messagingSenderId: '169717028719',
    projectId: 'walkapp-9a996',
    storageBucket: 'walkapp-9a996.appspot.com',
    iosBundleId: 'com.example.walkingapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAs4wsPGi8H63g--B9N2DT50fm9ZRNh6Mg',
    appId: '1:169717028719:web:af0d3a19c324f9e5fdfa9a',
    messagingSenderId: '169717028719',
    projectId: 'walkapp-9a996',
    authDomain: 'walkapp-9a996.firebaseapp.com',
    storageBucket: 'walkapp-9a996.appspot.com',
    measurementId: 'G-Q8SR4J0MQY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7KbwOCoFNF8uNPDsYCbhjdRQmCmuHqi8',
    appId: '1:169717028719:android:ae61eb8c3ac1fd78fdfa9a',
    messagingSenderId: '169717028719',
    projectId: 'walkapp-9a996',
    storageBucket: 'walkapp-9a996.appspot.com',
  );

}